  import type { Metadata } from 'next'
  import './globals.css'
  import Header from '@/components/header/header'
  import { Providers } from './providers'
import Navigation from '@/components/navigation/navigation'

  export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
          <div className='container mx-auto'>
            <Header />
            <div className='flex flex-row'>
              <div className='basis-1/5'>
                <Navigation />
              </div>
              <div className='basis-4/5'>
                <Providers>
                  {children}
                </Providers>
              </div>
            </div>
          </div>
        </body>
      </html>
    )
  }
