import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='container mx-auto'>
          <Header />
          <div className='flex flex-row'>
            <div className='basis-1/5'>
             menu
            </div>
            <div className='basis-4/5'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
